### ISSUE TITLE
[Feature Request]: Could we use different URL from search results when the first link can't be accessed via CURL

### ISSUE THREAD

**Issue by maheshhp** [tobiasbueschel/search-gpt#5]
When I try to search for `exit`, it tries to fetch content from the first search result and get's stuck in the process since CURL is not allowed. It could probably skip this link and try with the next one if this happens?

<img width="460" alt="image" src="https://user-images.githubusercontent.com/16649283/222919575-87b26304-7259-494a-bc6c-eabb889865d3.png">

<img width="958" alt="image" src="https://user-images.githubusercontent.com/16649283/222919528-8a73e3b8-c673-4c1e-9562-0862e3ed69be.png">

**Comment by lxfriday** [comment]
Perhaps the code can detect the returned HTTP status code and retry subsequent links up to three times if it is not met?

**Comment by tobiasbueschel** [comment]
Thanks @maheshhp for raising this & great idea @lxfriday - I've just pushed a fix for this issue: https://github.com/tobiasbueschel/search-gpt/commit/8e48f808e615974b5cedd0f548c3861b851e5e81
